<script src="../assets/js/jquery.min.js"></script>
<!-- <script src="assets/js/bootstrap.bundle.min.js"></script> -->
<script src="../assets/js/waypoints.min.js"></script>
<script src="../assets/js/jquery.easing.min.js"></script>
<script src="../assets/js/owl.carousel.min.js"></script>
<script src="../assets/js/jquery.counterup.min.js"></script>
<script src="../assets/js/jquery.countdown.min.js"></script>
<script src="../assets/js/default/jquery.passwordstrength.js"></script>
<script src="../assets/js/wow.min.js"></script>
<!-- <script src="assets/js/jarallax.min.js"></script> -->
<!-- <script src="assets/js/jarallax-video.min.js"></script> -->
<script src="../assets/js/default/dark-mode-switch.js"></script>
<script src="../assets/js/default/active.js"></script>
<!-- <script src="assets/js/pwa.js"></script> -->